added badge to status report

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,24 +16,39 @@ jobs:
         run: pip install -U pytest
 
       - name: add date
-        run: echo -e "\n__results from $(date +'%Y-%m-%d')__\n" >> $log_Output
+        run: |
+          echo -e "\n__results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} \n" >> $log_Output
+      
 
-      #runs the test and puts the output in a temporary file that will not be tracked by git
+      # runs the test and puts the output in a temporary file that will not be tracked by git
       - name: Run pytest
+        id  : pytest
         run : pytest > $temp_log
+      #
+      - name: add test fail badge
+        if: steps.step3.outcome == 'failure'
+        run: echo -e "\n![Static Badge](https://img.shields.io/badge/test-fail-red)\n" >> $log_Output
+
+      - name: add test fail badge
+        if: steps.step3.outcome == 'success'
+        run: echo -e "\n![Static Badge](https://img.shields.io/badge/test-pass-green)\n" >> $log_Output
 
       - name: config git
+        if: success() || failure()
         run: |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Actions"
 
       #the output log will be appended to the README.md in master so a checkout first is needed
       - name: checkout master
+        if: success() || failure()
         run: |
           git fetch
           git checkout master
 
+
       - name: append log to README
+        if: success() || failure()
         run : cat $temp_log >> $log_Output
 
       - name: commit logs
